# Generated by Django 4.0 on 2023-02-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_operator', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='DockingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_type', models.CharField(max_length=10)),
                ('ac_reg', models.CharField(max_length=10)),
                ('flight_no1', models.CharField(blank=True, max_length=10, null=True)),
                ('docked', models.DateTimeField(blank=True, null=True)),
                ('chocks_on', models.TimeField(blank=True, null=True)),
                ('flight_no2', models.CharField(blank=True, max_length=10, null=True)),
                ('door_close', models.TimeField(blank=True, null=True)),
                ('undocked', models.DateTimeField(blank=True, null=True)),
                ('no_docking', models.BooleanField(blank=True, default=False, null=True)),
                ('b_used', models.BooleanField(blank=True, default=False, null=True)),
                ('c_used', models.BooleanField(blank=True, default=False, null=True)),
                ('b_docked', models.TimeField(blank=True, null=True)),
                ('c_docked', models.TimeField(blank=True, null=True)),
                ('b_undocked', models.TimeField(blank=True, null=True)),
                ('c_undocked', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('operator1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser')),
                ('operator2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dockingRecords.secondoperator')),
                ('stand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.stand')),
            ],
        ),
    ]
