# Generated by Django 4.0 on 2023-02-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockingRecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockingrecord',
            name='b_door_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dockingrecord',
            name='c_door_close',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
