# Generated by Django 4.0 on 2023-02-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='ImportFiles/%Y/%m/%d')),
                ('accounts_file', models.BooleanField(blank=True, default=False, null=True)),
                ('locations_file', models.BooleanField(blank=True, default=False, null=True)),
                ('docking_records_file', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
